### ISSUE TITLE
Botão "Liberar" não permite determinar os parâmetros de modelagem

### ISSUE THREAD

**Issue by gmgall** [Model-R/Front-end#15]
Na aba de _Data Cleaning_ há um botão _Liberar_, que cria um experimento já liberado. Ele permite isso antes mesmo de se configurar os parâmetros de modelagem.

![captura de tela_2018-03-13_02-54-26](https://user-images.githubusercontent.com/973834/37324805-e2667824-2669-11e8-8f67-2eb9900b9c91.png)

É possível que um experimento seja criado sem nenhum algoritmo de modelagem selecionado dessa forma. Nesse caso, o web service informa `"algorithm": []` para o experimento.

Esse é o comportamento desejado? Parece-me que não. O botão deveria alertar que ainda faltam etapas do workflow de modelagem ou nem deveria estar ali.

**Comment by gmgall** [comment]
Na 1ª vez que a aba _Data Cleaning_ é usada, realmente o botão não aparece mais.

Mas após aplicar uma operação nos pontos (como liberá-los para modelagem) o botão reaparece e é possível liberá-lo sem configurar a modelagem novamente.

**Comment by antunesmg** [comment]
A partir de agora, os experimentos já são criados com parâmetros default.
