### ISSUE TITLE
Alterações feitas em um experimento não são salvas (ou são perdidas)

### ISSUE THREAD

**Issue by gmgall** [Model-R/Front-end#18]
Esse é um pouco mais difícil de reproduzir, mas talvez o mais grave. Algumas alterações em experimentos feitas na interface não são salvas.

Ainda não ficou claro para mim em que situações específicas o problema ocorre, mas o experimento abaixo, por exemplo, foi criado com um nome e é listado sem nome depois.

![captura de tela_2018-03-13_03-17-14](https://user-images.githubusercontent.com/973834/37325530-0eb7aa80-266d-11e8-8c91-54d62a4543e6.png)

Depois, até consegui colocar um nome nele e fui adicionar pontos de ocorrência. Coloquei 2 pontos e salvei. O experimento perdeu o nome. :exclamation:

**Comment by antunesmg** [comment]
Testei esses passos de criar um experimento e adicionar novos pontos, mas não encontrei o erro.
Comigo está funcionando.
Você fez aluma coisa diferente disso ?

**Comment by gmgall** [comment]
Como comentei, é um pouco difícil de reproduzir. Parece que acontece em situações distintas.

Consegui novamente aqui. Criei um experimento novo e adicionei pontos. Até aí ok.

Aí, fui até a aba _Modelagem_ e mudei algumas coisas. Salvei e o experimento perdeu o nome.

O problema é visto via web service também. O nome passa a vir vazio (`"name": ""` no JSON).
