### ISSUE TITLE
O método que muda o status de um experimento deixou de funcionar

### ISSUE THREAD

**Issue by gmgall** [Model-R/Front-end#19]
Tentei usar agora o método que muda o status de um experimento (`setstatus.php`) e recebi a seguinte exceção do Python:

```
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

Esse método funcionava. Mudou alguma coisa?

**Comment by antunesmg** [comment]
Pode mandar um exemplo de como você chama esse método ?

**Comment by antunesmg** [comment]
Guilherme, resolvi aqui.
Pode testar de novo, por favor. 
https://model-r.jbrj.gov.br/ws/setstatus.php?id=e2ef524fbf3d9fe611d5a8e90fefdc9c&status=1

**Comment by gmgall** [comment]
Agora de fato funcionou.

Testei da seguinte forma pelo shell:

```shell
$ curl 'https://model-r.jbrj.gov.br/ws/setstatus.php?id=bd4c9ab730f5513206b999ec0d90d1fb&status=4'
{"experiment":[{"idexperiment":"bd4c9ab730f5513206b999ec0d90d1fb","update": "true","msg": ""}]}
```

O código do Middleware, **que não mudou entre a abertura dessa issue e esse teste de agora**, também funcionou. Foi feita alguma alteração aí?

**Comment by diogosbr** [comment]
@gmgall e @antunesmg , podemos então fechar essa issue?

**Comment by diogosbr** [comment]
Pessoal?!  @gmgall @antunesmg

**Comment by antunesmg** [comment]
Por mim sim Diogo

**Comment by gmgall** [comment]
No momento, não consigo acessar model-r.jbrj.gov.br nem da minha máquina em casa, nem da no LNCC. Algum problema por aí?

```
$ curl 'https://model-r.jbrj.gov.br/ws/setstatus.php?id=bd4c9ab730f5513206b999ec0d90d1fb&status=4'
curl: (7) Failed to connect to model-r.jbrj.gov.br port 443: Não há rota para o host
```

**Comment by gmgall** [comment]
Na realidade, nem o [site do JB](http://www.jbrj.gov.br/) eu consigo acessar.

**Comment by antunesmg** [comment]
SIm, estava com problema no servidor aqui.
Parece que já voltou ao normal.

**Comment by gmgall** [comment]
Parece realmente funcional. Fecharei essa issue.

```
$ curl 'https://model-r.jbrj.gov.br/ws/setstatus.php?id=bd4c9ab730f5513206b999ec0d90d1fb&status=2'                                                                                                                                                                            
{"experiment":[{"idexperiment":"bd4c9ab730f5513206b999ec0d90d1fb","update": "true","msg": ""}]}
```
