### ISSUE TITLE
Criar método para obter experimentos por status

### ISSUE THREAD

**Issue by gmgall** [Model-R/Front-end#3]
Para obter os experimentos de interesse do Middleware, aqueles a serem processados (os com status _Liberado_), primeiro é necessário obter *todos os experimentos* e então fazer a filtragem.

Isso significa que informações desnecessárias são transmitidas. Hoje se tivermos, por exemplo, 1000 experimentos, apenas 1 _Liberado_ e 999 _Aguardando_, dados de todos os 1000 serão transmitidos.

Sugiro a criação de um método que permita obter todos os experimentos com um determinado status. Seria um uso mais eficiente da rede.

**Comment by rafaeloliveiralima** [comment]
Criei um o parâmetro = 'status'

Aceitamos os valores numéricos 
1;"Aguardando"
2;"Liberado"
3;"Em processamento"
4;"Processado"

http://model-r.jbrj.gov.br/ws/?status=2

**Comment by gmgall** [comment]
Acabo de testar pelo `curl` e parece funcional.

**Comment by rafaeloliveiralima** [comment]
Foi corrigido e estou fechando.
