### ISSUE TITLE
Trocar "long" por "lon"

### ISSUE THREAD

**Issue by gmgall** [Model-R/Front-end#8]
Para o Middleware escrever o CSV que será lido pelas funções de modelagem, uma lista de pontos de ocorrência é processada pela [`csv.DictWriter()` do Python](https://docs.python.org/2/library/csv.html#csv.DictWriter). Essa função recebe uma lista de campos a serem escritos no CSV.

A longitude vem do web service em um campo chamado `long`, mas as funções de modelagem só funcionam com `lon`. Com isso, preciso de um passo extra de trocar `long` por `lon` em todo ponto informado.

Sugiro que o web service já use `lon`.

**Comment by rafaeloliveiralima** [comment]
Alteração realizada!

**Comment by rafaeloliveiralima** [comment]
Fiz a alteração necessária.

**Comment by gmgall** [comment]
Testei via `curl` e constatei que a mudança foi feita.

Conseguirei usar a `csv.DictWriter()` diretamente agora.
