### ISSUE TITLE
Infraestrutura para disponibilização de dados espaciais

### ISSUE THREAD

**Issue by FelipeSBarros** [Model-R/Front-end#9]
Foi comentado na reunião do dia 05/09/2017 dificuldade com a infraestrutura usada para disponibilizar os dados gerados pela modelagem na interface gráfica de frontend;
Uma alternativa ao google maps, seria usar o [geoserver](http://geoserver.org/)
Com tal infraestrutura seria possivel disponibilizar: 
* os modelos gerados - *ou qualquer outra informação espacial em formato raster* - em seu formato "nativo" (até o presente momento [GeoTIFF](http://docs.geoserver.org/latest/en/user/data/raster/geotiff.html));
* dados vetoriais, seja em formato *[.shp](http://docs.geoserver.org/latest/en/user/data/vector/shapefile.html)*, como outros que estejam armazenados no [PostGIS](http://docs.geoserver.org/latest/en/user/data/database/postgis.html);

Com Geoserver pode-se usar protocolos [WFS-T](https://gis.stackexchange.com/questions/34283/whats-role-of-wfs-t-in-webapp), WPS para edição de mapas (pós-processamento) ao associado com [openlayers](http://openlayers.org), para visualização dos dados.
Compartilho uma imagem simples para tentar expor a respeito do Geoserver.
![](https://i.stack.imgur.com/hheTL.jpg)

**Comment by AndreaSanchezTapia** [comment]
Com isto aquela geração do .png "nu" e do objeto `extent()` que @rafaeloliveiralima e @diogosbr comentaram seria desnecessário? Fico no aguardo do teste do Rafael para saber.

**Comment by FelipeSBarros** [comment]
Teoricamente, sim @AndreaSanchezTapia . @rafaellima não sei como o Google maps dialoga com geoserver. Mas há outras aplicações que podemos adotar como alternativa ao gmaps. Qq coisa, me avise.

**Comment by rafaeloliveiralima** [comment]
@FelipeSBarros teríamos que instalar um servidor GeoServer em algum lugar ou usaríamos algum já existente?

**Comment by FelipeSBarros** [comment]
@rafaeloliveiralima Imagino que seja necessário ter o Geoserver instalado no servidor onde estarão os dados. 
Além disso, acho que vcs já devem ter o Gepserver instalado no JB. Talvez o CNCFlora o tenha?

**Comment by FelipeSBarros** [comment]
@rafaeloliveiralima estive pesquisando. No caso dos dados que estejam em banco de dados, não teríamos problemas. Poderíamos usar um Geoserver instalado em um servidor e o banco em outro, uma vez que ele teria acesso ao host, login e senha do geoserver para acessar os dados.

Mas como no caso dos rasters, vamos mante-los em dados "fisicos", precisaríamos ter o Geoserver na mesma "maquina". Veja a **URL** na imagem :
![](https://live.osgeo.org/_images/geoserver-netcdf-store.png)
